/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::PinnedAssetImage BlackTile;
extern const Sifteo::AssetImage Set1IdenticalObjects;
extern const Sifteo::AssetImage Set3SameShapeDifferentColors;
extern const Sifteo::AssetImage Set2SameColorDifferentShape;
extern const Sifteo::AssetImage Set4DifferentColorsAndShapes;
extern const Sifteo::AssetImage Set5SameShapeConflictsOnColor;
extern const Sifteo::AssetImage Set6SameColorConflictsOnShape;
extern const Sifteo::AssetImage Set7ConflictsOnShapeAndColor;
extern const Sifteo::AssetImage Backgrounds;
extern const Sifteo::PinnedAssetImage Bars[4];
extern const Sifteo::AssetAudio SfxAttach;
extern const Sifteo::AssetAudio SfxSong;
extern const Sifteo::AssetAudio SfxDetach;
extern const Sifteo::AssetAudio SfxConnect;
